-- OPEN WORKBENCH
CREATE DATABASE flipkarts;
USE flipkarts;
SELECT * FROM mobiles;

-- DIFFERENT PRICE RANGE SEGMENTS FOR MOBILES IN INDIA
SELECT brand,
SUM(CASE WHEN MRP BETWEEN 0 AND 9999 THEN 1 ELSE 0 END) AS 'Price Below 10k',
SUM(CASE WHEN MRP BETWEEN 10000 AND 19999 THEN 1 ELSE 0 END) AS 'Price Between 10-20k',
SUM(CASE WHEN MRP BETWEEN 20000 AND 39999 THEN 1 ELSE 0 END) AS 'Price Between 20-40k',
SUM(CASE WHEN MRP >= 40000 THEN 1 ELSE 0 END) AS 'Price above 40k'
FROM mobiles
GROUP BY brand 
ORDER BY brand;

-- THE BRAND THAT HAS THE HIGHEST DISCOUNT PRICE
SELECT brand, MAX(MRP-MSP)AS MaxDiscount
FROM mobiles 
GROUP BY brand 
ORDER BY MaxDiscount DESC
LIMIT 1;

-- TOP 5 BRANDS BY AVG RATING
SELECT Brand, avg(Ratings) AS Avg_Rating
FROM mobiles
GROUP BY brand 
ORDER BY Avg_Rating DESC 
LIMIT 5;

-- TOP 5 BRANDS BY AVG reviews
SELECT Brand, avg(No_of_reviews) AS Total_Reviews
FROM mobiles
GROUP BY brand 
ORDER BY Total_Reviews DESC 
LIMIT 5;

-- PRODUCTS WITH RATINGS GREATER THAN 4.5
SELECT * FROM mobiles
WHERE Ratings > 4.5;

-- PRODUCTS WITH DISCOUNTS GREATER THAN 40%
SELECT * FROM mobiles
WHERE Discount>40;

-- AVERAGE RATING AND NUMBER OF REVIEWS PER BRAND
SELECT Brand, AVG(Ratings) AS Avg_Rating, SUM(No_of_reviews) AS Total_Reviews
FROM mobiles
GROUP BY Brand
ORDER BY Avg_Rating DESC;

-- PRODUCTS WITH THE HIGHEST DISCOUNTS
SELECT * FROM mobiles
ORDER BY Discount DESC
LIMIT 5;

-- GET UNIQUE BRAND NAMES
SELECT DISTINCT Brand
FROM mobiles;